// Simplified bidding_auction_servers proto for secure invoke
syntax = "proto3";

package privacy_sandbox.bidding_auction_servers;

import "logger.proto";
import "generate_bid.proto";

enum ClientType {
  CLIENT_TYPE_UNKNOWN = 0;
  CLIENT_TYPE_BROWSER = 1;
  CLIENT_TYPE_ANDROID = 2;
}

message BuyerInput {
  repeated InterestGroup interest_groups = 1;
}

message ProtectedAppSignals {
  bytes app_install_signals = 1;
}

message ProtectedAppSignalsBuyerInput {
  ProtectedAppSignals protected_app_signals = 1;
}

message GetBidsRequest {
  message GetBidsRawRequest {
    bool is_chaff = 1;
    BuyerInput buyer_input = 2;
    string auction_signals = 3;
    string buyer_signals = 4;
    string seller = 5;
    string publisher_name = 6;
    bool enable_debug_reporting = 7;
    server_common.LogContext log_context = 8;
    server_common.ConsentedDebugConfiguration consented_debug_config = 9;
    ProtectedAppSignalsBuyerInput protected_app_signals_buyer_input = 10;
    ClientType client_type = 11;
    bool enable_unlimited_egress = 12;
  }
  
  bytes request_ciphertext = 1;
  string key_id = 2;
}

message AdWithBid {
  string ad_metadata = 1;
  float bid = 2;
  string render = 3;
  repeated string ad_components = 4;
  int32 modeling_signals = 5;
  string bid_currency = 6;
  string ad_cost = 7;
  float interest_group_origin = 8;
}

message GetBidsResponse {
  message GetBidsRawResponse {
    repeated AdWithBid bids = 1;
    map<string, string> ad_scoring_signals = 2;
  }
  
  bytes response_ciphertext = 1;
  string key_id = 2;
}
