# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: generate_bid.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'generate_bid.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12generate_bid.proto\x12\'privacy_sandbox.bidding_auction_servers\"J\n\x0e\x42rowserSignals\x12\x12\n\njoin_count\x18\x01 \x01(\x05\x12\x11\n\tbid_count\x18\x02 \x01(\x05\x12\x11\n\tprev_wins\x18\x03 \x01(\t\"\xc2\x01\n\rInterestGroup\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x1c\n\x14\x62idding_signals_keys\x18\x02 \x03(\t\x12\x1c\n\x14user_bidding_signals\x18\x03 \x01(\t\x12\x15\n\rad_render_ids\x18\x04 \x03(\t\x12P\n\x0f\x62rowser_signals\x18\x05 \x01(\x0b\x32\x37.privacy_sandbox.bidding_auction_servers.BrowserSignalsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'generate_bid_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BROWSERSIGNALS']._serialized_start=63
  _globals['_BROWSERSIGNALS']._serialized_end=137
  _globals['_INTERESTGROUP']._serialized_start=140
  _globals['_INTERESTGROUP']._serialized_end=334
# @@protoc_insertion_point(module_scope)
